### ISSUE TITLE
Some problems' names contain char like '?' '/' '*' will cause program terminate.

### ISSUE THREAD

**Issue by ScrapW** [ISKU/Codeforces-Solutions-Downloader#1]
For example: 1037D - Valid BFS?

**Comment by ISKU** [comment]
Hi @ScrapW 

Thank you for using the tool.
I have verified this issue on Ubuntu 18.04LTS. But I did not find any problems.

But if you are using Windows, there may be a problem.
On Windows, you can not use '\', '/', '?', '*', '<', '>', '|', '"', ':' in file names by default.
If you want the tool to fix this problem, you will need to change it to a different letter.
But, it does not mean the title of the original problem, so I think it's a bad way.
If you have a good idea, please tell me.

I recommend that you do not use the [TITLE] option for file names.
'[CONTEST] [INDEX]' seems to be the most suitable file name format.

**Comment by ScrapW** [comment]
When I save my programs I use full-width char to avoid this issue.
Like ：，／？＊｜＂＜＞

**Comment by ISKU** [comment]
Oh, it is a good idea.
I will fix it as soon as possible.
Thank you

**Comment by ScrapW** [comment]
Thank you for fixing it.
(I typed a wrong full-width char in the previous commit just now,now fixed.)
