### ISSUE TITLE
Problem with downloading Solutions.

### ISSUE THREAD

**Issue by Darklight256** [ISKU/Codeforces-Solutions-Downloader#5]
Hi!
I have a problem with downloading the solutions and when I want to run the process it saves only one of the solutions.

**Comment by ISKU** [comment]
Hi! @Darklight256 
Thank you for using this tool :D

If there are multiple correct source codes, select only the last submitted source code.
This is the default rule to avoid downloading all the correct source code you submitted.
Downloading all correct source code is very simple and can be supported in the future. This may require additional features such as options.

If you have a good idea, please let me know.
Thank you.
