### ISSUE TITLE
A problem with downloading ACMSGURU solutions.

### ISSUE THREAD

**Issue by Darklight256** [ISKU/Codeforces-Solutions-Downloader#6]
I fixed it!  :)
`        for submission in user_status:`
            `if not submission['verdict'] == 'OK' or len(submission['problem']['tags']) == 0:`
                `continue`
I replace this code with 36-38 lines of main.py
Now the solution of the problems without tags (Include: all of ACMSGURU problems), is not going to be download and it won't crashed out!

**Comment by ISKU** [comment]
Hi! @Darklight256 

Thank you very much for fixing this problem.
I can fix the code, and Merge the master branch. But you can also try a pull request.
This is an opportunity for you to contribute to the repository.

**Comment by ISKU** [comment]
This issue has been fixed here. c063d9f4bd66bc5970b6da10bdba4d9174fdea42
Thank you
